apiVersion: v1
kind: Service
metadata:
  labels:
      app: udagram-api-user
  name: backend-user
  namespace: udagram
spec:
  selector:
    service: udagram-api-user
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080