apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-api-feed-svc
  name: backend-feed
  namespace: udagram
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-api-feed